// Static configuration for all 29 days of the healing journey

import type { DayConfig } from '@/types'

export const DAYS: readonly DayConfig[] = [
  // ─── Stage: Emergency (Days 1-3) ──────────────────────────────────
  {
    dayNumber: 1,
    theme: '情绪气象播报',
    subtitle: '给你的心情画一幅天气图',
    guidanceText: '今天不需要做任何改变，只需要诚实地感受。录一段语音或写几句话，描述此刻你的内心像什么天气。',
    stageId: 'emergency',
    icon: '🌦️',
    tags: ['情绪觉察', '自我表达', '语音记录'],
    estimatedMinutes: 10,
  },
  {
    dayNumber: 2,
    theme: '最低生存清单',
    subtitle: '完成三件小事，就是胜利',
    guidanceText: '失恋后最难的是日常。今天只需完成三件事：吃一顿饭、喝够水、洗个澡。每完成一项就打个勾。',
    stageId: 'emergency',
    icon: '✅',
    tags: ['自我照顾', '基础需求', '打卡'],
    estimatedMinutes: 5,
  },
  {
    dayNumber: 3,
    theme: '沉默的陪伴',
    subtitle: '你不需要说话，只需要有人在',
    guidanceText: '给一个信任的朋友发条消息，或者只是感受"有人在"的安心。陪伴不一定需要语言。',
    stageId: 'emergency',
    icon: '🤝',
    tags: ['社交连接', '陪伴', '信任'],
    estimatedMinutes: 10,
  },
  // ─── Stage: Rebuild (Days 4-6) ────────────────────────────────────
  {
    dayNumber: 4,
    theme: '告别信',
    subtitle: '写一封永远不会寄出的信',
    guidanceText: '把想说的话都写下来，不需要逻辑，不需要体面。这封信只属于你，写完就放下。',
    stageId: 'rebuild',
    icon: '✉️',
    tags: ['情绪释放', '写作疗愈', '告别'],
    estimatedMinutes: 20,
  },
  {
    dayNumber: 5,
    theme: '物品告别',
    subtitle: '给一件旧物找到新的归宿',
    guidanceText: '选一件让你想起ta的物品，拍张照片，然后决定它的去处：收起来、丢掉、还是改造它。',
    stageId: 'rebuild',
    icon: '📦',
    tags: ['断舍离', '仪式感', '放手'],
    estimatedMinutes: 15,
  },
  {
    dayNumber: 6,
    theme: '作息重启',
    subtitle: '设计一个只属于你的晨间仪式',
    guidanceText: '过去的早晨可能和ta有关，现在重新定义它。列出3-5件你想在每天早上做的事。',
    stageId: 'rebuild',
    icon: '🌅',
    tags: ['习惯养成', '作息', '新节奏'],
    estimatedMinutes: 10,
  },
  // ─── Stage: Energy (Days 7-9) ─────────────────────────────────────
  {
    dayNumber: 7,
    theme: '身体扫描冥想',
    subtitle: '和身体重新对话',
    guidanceText: '闭上眼睛，从头顶到脚尖慢慢扫描。注意哪里紧绷、哪里酸痛。你的身体一直在替你承受。',
    stageId: 'energy',
    icon: '🧘',
    tags: ['冥想', '身体觉察', '放松'],
    estimatedMinutes: 15,
  },
  {
    dayNumber: 8,
    theme: '感恩清单',
    subtitle: '写下三件今天值得感恩的事',
    guidanceText: '即使在最灰暗的日子里，也有微小的光。一杯热茶、一个善意的微笑、窗外的阳光。',
    stageId: 'energy',
    icon: '🙏',
    tags: ['感恩', '正念', '积极心理'],
    estimatedMinutes: 10,
  },
  {
    dayNumber: 9,
    theme: '内在小孩对话',
    subtitle: '和小时候的自己聊聊天',
    guidanceText: '想象5岁的自己坐在你面前，ta会对你说什么？你又想对ta说什么？写下这段对话。',
    stageId: 'energy',
    icon: '👶',
    tags: ['内在小孩', '自我对话', '情绪疗愈'],
    estimatedMinutes: 20,
  },
  // ─── Stage: Deep Healing (Days 10-12) ─────────────────────────────
  {
    dayNumber: 10,
    theme: '能量审计',
    subtitle: '找出你的能量黑洞和充电站',
    guidanceText: '列出最近消耗你能量的事和人，再列出给你充电的事和人。减少前者，增加后者。',
    stageId: 'deep-healing',
    icon: '🔋',
    tags: ['能量管理', '自我觉察', '边界'],
    estimatedMinutes: 15,
  },
  {
    dayNumber: 11,
    theme: '边界练习',
    subtitle: '学会说"不"',
    guidanceText: '写下三句你想要但不敢说的拒绝话语。大声读出来。设立边界不是自私，是自爱。',
    stageId: 'deep-healing',
    icon: '🛡️',
    tags: ['边界', '自我保护', '沟通'],
    estimatedMinutes: 15,
  },
  {
    dayNumber: 12,
    theme: '自我疗愈信',
    subtitle: '给自己写一封温柔的信',
    guidanceText: '用第二人称写给自己：亲爱的，你已经做得很好了……不要评判，只要温柔。',
    stageId: 'deep-healing',
    icon: '💌',
    tags: ['自我关怀', '写作疗愈', '自我接纳'],
    estimatedMinutes: 20,
  },
  // ─── Stage: Review (Days 13-14) ───────────────────────────────────
  {
    dayNumber: 13,
    theme: '记忆重构',
    subtitle: '用新的视角看旧的回忆',
    guidanceText: '选一段让你痛苦的回忆，尝试从旁观者的角度重新描述它。你会发现新的理解。',
    stageId: 'review',
    icon: '🔄',
    tags: ['认知重构', '记忆', '新视角'],
    estimatedMinutes: 20,
  },
  {
    dayNumber: 14,
    theme: '中途回望',
    subtitle: '你已经走过了一半',
    guidanceText: '回顾过去13天，你有什么变化？写下你的感受，给自己的进步打个分。',
    stageId: 'review',
    icon: '🔭',
    tags: ['反思', '里程碑', '自我评估'],
    estimatedMinutes: 15,
  },
  // ─── Stage: Disillusion (Days 15-17) ──────────────────────────────
  {
    dayNumber: 15,
    theme: '愤怒释放',
    subtitle: '允许自己生气',
    guidanceText: '愤怒是正常的情绪，不需要压制。选择一种方式释放：写下来、运动、画出来、大声说出来。',
    stageId: 'disillusion',
    icon: '🔥',
    tags: ['情绪释放', '愤怒', '表达'],
    estimatedMinutes: 15,
  },
  {
    dayNumber: 16,
    theme: '宽恕探索',
    subtitle: '宽恕不是为了ta，是为了你自己',
    guidanceText: '宽恕不意味着原谅一切。它是你放下重担的过程。思考：你想宽恕谁？自己、对方、还是两者？',
    stageId: 'disillusion',
    icon: '🕊️',
    tags: ['宽恕', '释怀', '内心平静'],
    estimatedMinutes: 20,
  },
  {
    dayNumber: 17,
    theme: '社会身份找回',
    subtitle: '你不只是某人的前任',
    guidanceText: '列出5个和感情无关的特质：你的技能、爱好、性格优点。你是完整的个体。',
    stageId: 'disillusion',
    icon: '🪞',
    tags: ['身份认同', '自我价值', '独立'],
    estimatedMinutes: 15,
  },
  // ─── Stage: Desensitize (Days 18-19) ──────────────────────────────
  {
    dayNumber: 18,
    theme: '感官脱敏',
    subtitle: '温和地面对触发点',
    guidanceText: '识别一个会触发你情绪的场景（一首歌、一个地方），有意识地接触它，观察情绪变化。',
    stageId: 'desensitize',
    icon: '🎯',
    tags: ['脱敏', '情绪管理', '勇敢面对'],
    estimatedMinutes: 20,
  },
  {
    dayNumber: 19,
    theme: '未来自己可视化',
    subtitle: '想象一个月后的你',
    guidanceText: '闭上眼睛，想象1个月/3个月/1年后的你在做什么。把这幅画面写下来，越具体越好。',
    stageId: 'desensitize',
    icon: '🔮',
    tags: ['未来', '想象力', '目标感'],
    estimatedMinutes: 15,
  },
  // ─── Stage: Reorganize (Days 20-23) ───────────────────────────────
  {
    dayNumber: 20,
    theme: '价值观重新对齐',
    subtitle: '什么对你来说真正重要？',
    guidanceText: '从一组价值观卡片中选出你最看重的5个，然后为每个写下一个具体的行动计划。',
    stageId: 'reorganize',
    icon: '🧭',
    tags: ['价值观', '自我探索', '方向'],
    estimatedMinutes: 20,
  },
  {
    dayNumber: 21,
    theme: '创造性表达',
    subtitle: '用艺术说话',
    guidanceText: '选择一种创作方式：画画、写诗、拍照、做手工、弹琴……不要评判，只要表达。',
    stageId: 'reorganize',
    icon: '🎨',
    tags: ['创造力', '艺术疗愈', '表达'],
    estimatedMinutes: 30,
  },
  {
    dayNumber: 22,
    theme: '关系模式分析',
    subtitle: '看见你的感情模式',
    guidanceText: '回顾过去的感情经历，你发现了什么重复的模式？写下你的观察和洞见。',
    stageId: 'reorganize',
    icon: '🔍',
    tags: ['关系模式', '自我觉察', '洞察'],
    estimatedMinutes: 20,
  },
  {
    dayNumber: 23,
    theme: '舒适区挑战',
    subtitle: '做一件你从未做过的事',
    guidanceText: '选一个小挑战：去一家新餐厅、和陌生人聊天、尝试新运动。记录你的体验和感受。',
    stageId: 'reorganize',
    icon: '🚀',
    tags: ['突破', '新体验', '成长'],
    estimatedMinutes: 30,
  },
  // ─── Stage: Awakening (Days 24-27) ────────────────────────────────
  {
    dayNumber: 24,
    theme: '支持网络地图',
    subtitle: '画出你的人际支持图',
    guidanceText: '画三个同心圆：核心圈（最亲密的人）、外圈（朋友同事）、新连接（想要认识的人）。',
    stageId: 'awakening',
    icon: '🗺️',
    tags: ['社交网络', '人际关系', '支持系统'],
    estimatedMinutes: 15,
  },
  {
    dayNumber: 25,
    theme: '里程碑庆祝',
    subtitle: '你值得被庆祝！',
    guidanceText: '列出这25天里你完成的所有成就（无论多小），然后选一种方式奖励自己。',
    stageId: 'awakening',
    icon: '🎉',
    tags: ['庆祝', '成就', '自我奖励'],
    estimatedMinutes: 15,
  },
  {
    dayNumber: 26,
    theme: '触发管理计划',
    subtitle: '为未来的情绪波动做好准备',
    guidanceText: '列出可能的情绪触发点和对应的应对策略。下次被触发时，你会知道该怎么做。',
    stageId: 'awakening',
    icon: '📋',
    tags: ['预防', '情绪管理', '计划'],
    estimatedMinutes: 20,
  },
  {
    dayNumber: 27,
    theme: '成长叙事',
    subtitle: '用你的话讲述这段旅程',
    guidanceText: '写一篇短文，讲述你从第1天到现在的变化故事。你是这个故事的主角和英雄。',
    stageId: 'awakening',
    icon: '📖',
    tags: ['叙事疗法', '成长', '故事'],
    estimatedMinutes: 25,
  },
  // ─── Stage: Restart (Days 28-29) ──────────────────────────────────
  {
    dayNumber: 28,
    theme: '遗书般的信',
    subtitle: '写给过去或未来的自己',
    guidanceText: '选一个收信人：过去的自己、未来的自己、或者曾经的ta。把最后想说的话写完。',
    stageId: 'restart',
    icon: '📜',
    tags: ['告别', '写作', '仪式感'],
    estimatedMinutes: 20,
  },
  {
    dayNumber: 29,
    theme: '新的开始宣言',
    subtitle: '29天，你做到了',
    guidanceText: '写下你的新开始宣言：你是谁、你想要什么、你将走向哪里。大声读出来，为自己鼓掌。',
    stageId: 'restart',
    icon: '🌱',
    tags: ['新开始', '宣言', '未来'],
    estimatedMinutes: 15,
  },
] as const

/** Look up a day's configuration by its number */
export const getDayConfig = (dayNumber: number): DayConfig | undefined =>
  DAYS.find((day) => day.dayNumber === dayNumber)

/** Get all days belonging to a specific stage */
export const getDaysByStage = (stageId: string): readonly DayConfig[] =>
  DAYS.filter((day) => day.stageId === stageId)
